package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/startower-observability/blackcat/internal/types"
)

// MaxReplanAttempts is the maximum number of times the planner can re-plan
// after a step failure before giving up.
const MaxReplanAttempts = 1

// PlanStepStatus represents the execution state of a plan step.
type PlanStepStatus string

const (
	StepPending    PlanStepStatus = "pending"
	StepInProgress PlanStepStatus = "in_progress"
	StepCompleted  PlanStepStatus = "completed"
	StepFailed     PlanStepStatus = "failed"
	StepSkipped    PlanStepStatus = "skipped"
)

// PlanStep is one step in a multi-step execution plan.
type PlanStep struct {
	Index       int            `json:"index"`
	Description string         `json:"description"`
	ToolName    string         `json:"tool_name,omitempty"`
	ToolArgs    string         `json:"tool_args,omitempty"`
	Status      PlanStepStatus `json:"status"`
	Result      string         `json:"result,omitempty"`
	Error       string         `json:"error,omitempty"`
}

// Plan is a structured multi-step plan generated by the LLM.
type Plan struct {
	Goal           string     `json:"goal"`
	Steps          []PlanStep `json:"steps"`
	CreatedAt      time.Time  `json:"created_at"`
	ReplanCount    int        `json:"replan_count"`
	CurrentStepIdx int        `json:"current_step_idx"`
}

// IsComplete returns true when all steps are completed, failed, or skipped.
func (p *Plan) IsComplete() bool {
	if p == nil || len(p.Steps) == 0 {
		return true
	}
	for _, s := range p.Steps {
		if s.Status == StepPending || s.Status == StepInProgress {
			return false
		}
	}
	return true
}

// Summary returns a human-readable summary of the plan and step statuses.
func (p *Plan) Summary() string {
	if p == nil || len(p.Steps) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString(fmt.Sprintf("Plan: %s\n", p.Goal))
	for _, s := range p.Steps {
		icon := "[ ]"
		switch s.Status {
		case StepCompleted:
			icon = "[+]"
		case StepFailed:
			icon = "[X]"
		case StepInProgress:
			icon = "[>]"
		case StepSkipped:
			icon = "[-]"
		}
		b.WriteString(fmt.Sprintf("  %s %d. %s", icon, s.Index+1, s.Description))
		if s.ToolName != "" {
			b.WriteString(fmt.Sprintf(" (tool: %s)", s.ToolName))
		}
		b.WriteByte('\n')
	}
	return strings.TrimSpace(b.String())
}

// Planner generates structured plans for complex tasks and can replan on failure.
type Planner struct {
	llm types.LLMClient
}

// NewPlanner creates a Planner. A nil llm makes Plan/Replan return nil plans.
func NewPlanner(llm types.LLMClient) *Planner {
	return &Planner{llm: llm}
}

// complexTaskKeywords are phrases that indicate a request is multi-step.
var complexTaskKeywords = []string{
	"step by step",
	"plan",
	"first", "then", "after that", "finally",
	"multiple",
	"create and deploy",
	"set up",
	"migrate",
	"refactor and test",
	"build and deploy",
}

// IsComplexTask returns true if the message appears to describe a multi-step task.
func IsComplexTask(msg string) bool {
	lower := strings.ToLower(msg)

	// Heuristic 1: contains planning-related phrases
	for _, kw := range complexTaskKeywords {
		if strings.Contains(lower, kw) {
			return true
		}
	}

	// Heuristic 2: multiple sentences (3+) suggest a complex request
	sentences := strings.FieldsFunc(msg, func(r rune) bool {
		return r == '.' || r == '!' || r == '?'
	})
	nonEmpty := 0
	for _, s := range sentences {
		if strings.TrimSpace(s) != "" {
			nonEmpty++
		}
	}
	if nonEmpty >= 3 {
		return true
	}

	return false
}

// planPromptTemplate is the system prompt for plan generation.
const planPromptTemplate = `You are a planning agent. Given a user request, generate a step-by-step execution plan as JSON.

Rules:
- Each step should be a single, clear action.
- If a step uses a tool, include the tool_name and tool_args fields.
- Steps without a specific tool should omit tool_name and tool_args.
- Keep the plan concise: 2-8 steps maximum.
- Set all step statuses to "pending".
- The goal field should be a one-sentence summary of the overall objective.

Respond ONLY with valid JSON matching this schema (no markdown, no backticks, no explanation):
{"goal":"...","steps":[{"index":0,"description":"...","tool_name":"...","tool_args":"...","status":"pending"}]}`

// GeneratePlan asks the LLM to produce a structured plan for the given task.
// Returns nil plan (not error) if the LLM is nil.
func (p *Planner) GeneratePlan(ctx context.Context, userMessage string, availableTools []types.ToolDefinition) (*Plan, error) {
	if p == nil || p.llm == nil {
		return nil, nil
	}

	// Build a tool list summary for context
	var toolSummary strings.Builder
	if len(availableTools) > 0 {
		toolSummary.WriteString("\nAvailable tools:\n")
		for _, td := range availableTools {
			toolSummary.WriteString(fmt.Sprintf("- %s: %s\n", td.Name, td.Description))
		}
	}

	messages := []types.LLMMessage{
		{Role: "system", Content: planPromptTemplate + toolSummary.String()},
		{Role: "user", Content: userMessage},
	}

	resp, err := p.llm.Chat(ctx, messages, nil)
	if err != nil {
		return nil, fmt.Errorf("planner: generate plan: %w", err)
	}

	plan, parseErr := parsePlanJSON(resp.Content)
	if parseErr != nil {
		slog.WarnContext(ctx, "planner: failed to parse plan JSON, falling back to non-plan execution",
			"err", parseErr, "raw", truncatePlanner(resp.Content, 200))
		return nil, nil // graceful degradation: treat as simple task
	}

	plan.CreatedAt = time.Now()
	return plan, nil
}

// Replan modifies an existing plan after a step failure, asking the LLM to adjust
// remaining steps. Returns nil if replanning is not possible or max attempts reached.
func (p *Planner) Replan(ctx context.Context, plan *Plan, failedStep PlanStep, userMessage string) (*Plan, error) {
	if p == nil || p.llm == nil || plan == nil {
		return nil, nil
	}

	if plan.ReplanCount >= MaxReplanAttempts {
		slog.InfoContext(ctx, "planner: max replan attempts reached", "replan_count", plan.ReplanCount)
		return nil, nil
	}

	replanPrompt := fmt.Sprintf(
		`The following plan was being executed but step %d failed.
Original goal: %s
Failed step: %s
Error: %s

Please generate a revised plan to achieve the original goal, taking into account the failure. Skip or modify the failed step.
Respond ONLY with valid JSON matching the same schema as before.`,
		failedStep.Index+1, plan.Goal, failedStep.Description, failedStep.Error)

	// Include completed steps as context
	var completed strings.Builder
	for _, s := range plan.Steps {
		if s.Status == StepCompleted {
			completed.WriteString(fmt.Sprintf("- Step %d (done): %s\n", s.Index+1, s.Description))
		}
	}
	if completed.Len() > 0 {
		replanPrompt += "\n\nAlready completed:\n" + completed.String()
	}

	messages := []types.LLMMessage{
		{Role: "system", Content: planPromptTemplate},
		{Role: "user", Content: replanPrompt},
	}

	resp, err := p.llm.Chat(ctx, messages, nil)
	if err != nil {
		return nil, fmt.Errorf("planner: replan: %w", err)
	}

	newPlan, parseErr := parsePlanJSON(resp.Content)
	if parseErr != nil {
		slog.WarnContext(ctx, "planner: failed to parse replan JSON", "err", parseErr)
		return nil, nil
	}

	newPlan.CreatedAt = time.Now()
	newPlan.ReplanCount = plan.ReplanCount + 1
	return newPlan, nil
}

// parsePlanJSON parses a JSON plan from the LLM response, handling common quirks
// like markdown code fences.
func parsePlanJSON(raw string) (*Plan, error) {
	// Strip markdown code fences if present
	cleaned := strings.TrimSpace(raw)
	if strings.HasPrefix(cleaned, "```") {
		// Remove opening fence (with optional language tag)
		if idx := strings.Index(cleaned, "\n"); idx >= 0 {
			cleaned = cleaned[idx+1:]
		}
		// Remove closing fence
		if idx := strings.LastIndex(cleaned, "```"); idx >= 0 {
			cleaned = cleaned[:idx]
		}
		cleaned = strings.TrimSpace(cleaned)
	}

	var plan Plan
	if err := json.Unmarshal([]byte(cleaned), &plan); err != nil {
		return nil, fmt.Errorf("invalid plan JSON: %w", err)
	}

	if len(plan.Steps) == 0 {
		return nil, fmt.Errorf("plan has no steps")
	}

	// Normalize step indices and statuses
	for i := range plan.Steps {
		plan.Steps[i].Index = i
		if plan.Steps[i].Status == "" {
			plan.Steps[i].Status = StepPending
		}
	}

	return &plan, nil
}

// truncatePlanner truncates a string for log output.
func truncatePlanner(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}

// ShouldPlan is a nil-safe method that returns true if the user message
// appears to describe a multi-step task that warrants plan generation.
// Returns false if the planner is nil.
func (p *Planner) ShouldPlan(msg string) bool {
	if p == nil {
		return false
	}
	return IsComplexTask(msg)
}

// FormatPlanForPrompt renders a Plan as a structured markdown block suitable for
// injection into the user message. Returns "" if plan is nil or has no steps.
func FormatPlanForPrompt(plan *Plan) string {
	if plan == nil || len(plan.Steps) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("### Execution Plan\n")
	b.WriteString(fmt.Sprintf("Goal: %s\n\n", plan.Goal))
	b.WriteString("Steps:\n")
	for _, step := range plan.Steps {
		b.WriteString(fmt.Sprintf("%d. %s", step.Index+1, step.Description))
		if step.ToolName != "" {
			b.WriteString(fmt.Sprintf(" (tool: %s)", step.ToolName))
		}
		b.WriteByte('\n')
	}
	return strings.TrimSpace(b.String())
}